#app:
 #   resource: "@AppBundle/Controller/"
  #  type:     annotation

api:
     resource: "@ApiBundle/Controller/"
     type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation