# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        UserBundle\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers

    providers:
        our_db_provider:
            entity:
                class: UserBundle:User
                property: username

    firewalls:
        secured_area:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   logout #route to logout
                target: admin_post_index
            anonymous: ~
            provider: our_db_provider
 #       main:
 #           anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        #putting security in the controller class instead!
#        - { path: ^/admin, roles: ROLE_USER }